{{- if and .Values.ingress.enabled (eq .Values.ingress.type "IngressRoute") }}
{{- $fullName := include "generic-app.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  commonName: {{ $fullName }}
  secretName: {{ $fullName }}-cert
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}