{{- if .Values.env }}
{{ $values := .Values }}
{{- $fullName := include "generic-app.fullname" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}
data:
  {{- range $key, $value := $values.env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}