{{- if and .Values.ingress.enabled (eq .Values.ingress.type "IngressRoute") }}
{{- $fullName := include "generic-app.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ $fullName }}-cert
  routes:
    {{- range .Values.ingress.hosts }}
    - kind: Rule
      match: Host(`{{ . }}`)
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - name: {{ $fullName }}
          port: {{ $.Values.port }}
    {{- end }}
{{- end }}