{{- if and .Values.serviceAccount.create .Values.serviceAccount.authorizedRules -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "generic-app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "generic-app.fullname" . }}
{{- if .Values.serviceAccount.authorizedRulesExtraNamespaces }}
{{- range .Values.serviceAccount.authorizedRulesExtraNamespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "generic-app.fullname" $ }}
  namespace: {{ . }}
  labels:
    {{- include "generic-app.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "generic-app.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "generic-app.fullname" $ }}
{{- end }}
{{- end }}
{{- end }}