{{- if .Values.envEncrypted }}
{{- $fullName := include "generic-app.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    {{- range $key, $value := .Values.envEncrypted }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      name: {{ $fullName }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
{{- end }}
