global:
  storageClass: ""

image: hello-world
tag: latest
port: 80
replicas: 1
command: []
args: []
updateStrategy:
  type: RollingUpdate
resources:
  preset: "micro" # nano, micro, small, medium, large, xlarge, 2xlarge
  enableCpuLimit: false
ingress:
  enabled: true
  annotations: {}
  keycloakProtection: false
  https: true
  hosts:
    - hello-world.com
  type: Ingress # or IngressRoute
  redirections: []
#    - from:
#        - www.crty.dev
#      to: crty.dev
healthCheckPath: ""
prometheus:
  enabled: false
  port: 80
  path: "/metrics"
serviceAccount:
  create: false
  name: ""
  authorizedRules: []
  annotations: {}
  authorizedRulesExtraNamespaces: []
securityContext: {}
#  runAsUser: ""
webdevopsPhpProductionEnvs: false
trustedProxiesEnv: false
env: {}
#  ENV_VAR: value
envEncrypted: {}
#  ENV_VAR: encrypted_value using sealed-secrets
workers: {}
#  consumer:
#    command:
#     - echo
#     - "hello world"
#    replicas: 1
cronJobs: {}
#  cron-1:
#    command:
#     - echo
#     - "hello world"
#    schedule: "* * * * *"
volumes: {}
#  data:
#    size: 1Gi
#    storageClass: "" # default is "gp2"
#    s3Driver:
#      bucket: "awstudio-cms-public-files"
#      region: "eu-west-3"
#      prefix: "${APP_NAME}"
#      hostCache: false
#    mountPath: /data
initContainers: {}
pdb:
  enabled: false